CREATE DATABASE Music

CREATE TABLE ARTISTS(
    AID INT PRIMARY KEY ,
    NAME VARCHAR(255),
    DOB DATE,
    BIO TEXT
);
CREATE TABLE SONGS(
    AID INT PRIMARY KEY ,
    NAME VARCHAR(255),
    DOR DATE,
    COVER INT
    
);
CREATE TABLE USERS(
    UID INT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255)
);
